### ISSUE TITLE
Diagram magnification does not work

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos-widget-tieto#1]
When navigating to a page in tietotermit, e.g. https://finto.fi/tt/fi/page/t77

- You should be able to see the diagram embedded under the concept information
- But when you click the diagram to view it in a separate pop-up, you will get a blank image with concole warnings about mixed content (http image within a https page)
- The widget.js seems to [refer to the image files](https://github.com/NatLibFi/Skosmos-widget-tieto/blob/f526b861a0ad4e375e8bbd7a9a5c3e2b133ffa90/widget.js#L43) with http protocol
- Switching the uri references to // instead of http:// should fix the problem

**Comment by kouralex** [comment]
Fixed this in https://github.com/NatLibFi/Skosmos-widget-tieto/commit/41a29f56839c549b6c57d510e27d466da9fc7a8d.

Additionally required setting the `Content-Security-Policy`/`X-Frame-Options` headers at the server for the iframe to be able to be shown.
